### ISSUE TITLE
Access to all available properties of SimHub (was: Custom ncalc properties)

### ISSUE THREAD

**Issue by alexkleinwaechter** [pre-martin/SimHubPropertyServer#13]
Hi,
It would be great if the custom ncalc properties could be exposed. Then we could convert text values to integers in Simhub. 

best!
Alex

**Comment by pre-martin** [comment]
Hi. Nice feature request.

You mean properties like `DataCorePlugin.ExternalScript.BlinkingGear` or `DataCorePlugin.ExternalScript.BlinkingGearUP`, which are created by `SimHub\NCalcScripts\samples.ini`?

**Comment by alexkleinwaechter** [comment]
Yes, exactly! In some games you get arrays of values or just text for some
properties. With ncalc it’s quite easy to transform them. But I have no
clue if you can grab these properties with your plug-in. Would be nice
though.

Best!
Alex

Martin ***@***.***> schrieb am Mi. 11. Jan. 2023 um 23:44:

**Comment by pre-martin** [comment]
I am able to access these values from my plugin. I need some additional logic (and a better investigation), but I will implement this feature.

**Comment by alexkleinwaechter** [comment]
Thank you for your work! I tested your software with Streamdeck XL and
BeamNG and it worked well. I am a .Net developer too.  I browsed through
your code and it’s a very clean and well written implementation. Congrats!

Alex.

**Comment by pre-martin** [comment]
I just wrote a small prototype and I am now able to access all properties that exist in SimHub under "Available properties":

![generic-property](https://user-images.githubusercontent.com/5703553/212186742-cd1da4b2-22ba-409e-abbd-7e2a3df8a879.png)

But these properties do not have a specific type, they are returned as `object` and they can take any value (see screenshot). This means, that I have to update my Stream Deck plugin too, so that it can handle this new property type `object`. It will take a few days for this release, so I ask you for some patience.

**Comment by pre-martin** [comment]
The plugin now allows access to all available SimHub properties. This includes the original request in this ticket ("Custom ncalc properties").

**Comment by pre-martin** [comment]
The code is not yet pushed or merged. I updated my Stream Deck plugin yesterday evening, so I hope that I can push and merge the changes for both projects this evening.
